# -*- coding: utf-8 -*-
"""DL_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNOge9d5tzYNh0xLlOSUZtBsc8-nLZWC
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt

print("Loading STL-10 Dataset...")

(ds_train, ds_test), ds_info = tfds.load(
    'stl10',
    split=['train', 'test'],
    as_supervised=True,
    with_info=True
)

class_names = ['Airplane', 'Bird', 'Car',   'Cat',  'Deer',
               'Dog',      'Horse','Monkey', 'Ship', 'Truck']

print(f"Train size : {ds_info.splits['train'].num_examples}")
print(f"Test size  : {ds_info.splits['test'].num_examples}")
print(f"Classes    : {class_names}")

IMG_SIZE   = 96
BATCH_SIZE = 32

def preprocess(image, label):
    image = tf.cast(image, tf.float32)
    image = tf.image.resize(image, [IMG_SIZE, IMG_SIZE])
    image = tf.keras.applications.resnet50.preprocess_input(image)
    return image, label

train_ds = (ds_train
            .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
            .shuffle(500)
            .batch(BATCH_SIZE)
            .prefetch(tf.data.AUTOTUNE))

test_ds  = (ds_test
            .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
            .batch(BATCH_SIZE)
            .prefetch(tf.data.AUTOTUNE))

sample_images, sample_labels = next(iter(
    ds_train.batch(10).take(1)
))

plt.figure(figsize=(12, 2))
for i in range(10):
    plt.subplot(1, 10, i + 1)
    plt.imshow(sample_images[i].numpy())
    plt.title(class_names[sample_labels[i]], fontsize=7)
    plt.axis('off')
plt.suptitle('Sample STL-10 Images', fontweight='bold')
plt.tight_layout()
plt.show()

print("\nLoading ResNet50 (ImageNet weights)...")

base_model = tf.keras.applications.ResNet50(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights='imagenet'
)

print(f"Total Layers : {len(base_model.layers)}")
print(f"Total Params : {base_model.count_params():,}")

base_model.trainable = False
print(f"\nPhase 1 - Base Model : FROZEN")

model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(10,  activation='softmax')  # 10 STL classes
], name='ResNet50_STL10')

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

print("\nPhase 1: Training Head Only...")
history_frozen = model.fit(
    train_ds,
    epochs=10,
    validation_data=test_ds,
    verbose=1
)

loss_frozen, acc_frozen = model.evaluate(test_ds, verbose=0)
print(f"\nPhase 1 → Accuracy: {acc_frozen*100:.2f}% | Loss: {loss_frozen:.4f}")

base_model.trainable = True
for layer in base_model.layers[:-20]:
    layer.trainable = False

trainable = sum(1 for l in base_model.layers if l.trainable)
print(f"\nPhase 2 - Last 20 Layers : UNFROZEN")
print(f"Trainable Layers         : {trainable}")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("\nPhase 2: Fine-tuning Last 20 Layers...")
history_finetune = model.fit(
    train_ds,
    epochs=10,
    validation_data=test_ds,
    verbose=1
)

loss_finetune, acc_finetune = model.evaluate(test_ds, verbose=0)
print(f"\nPhase 2 → Accuracy: {acc_finetune*100:.2f}% | Loss: {loss_finetune:.4f}")

all_val_loss = (history_frozen.history['val_loss'] +
                history_finetune.history['val_loss'])
all_val_acc  = (history_frozen.history['val_accuracy'] +
                history_finetune.history['val_accuracy'])

phase1_end = len(history_frozen.history['val_loss'])

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Loss
axes[0].plot(all_val_loss, color='steelblue', linewidth=2, label='Val Loss')
axes[0].axvline(x=phase1_end, color='red',
                linestyle='--', linewidth=2, label='Fine-tune Start')
axes[0].set_title('Validation Loss')
axes[0].set_xlabel('Epochs')
axes[0].set_ylabel('Loss')
axes[0].legend()
axes[0].grid(True, linestyle='--', alpha=0.5)

# Accuracy
axes[1].plot(all_val_acc, color='darkorange', linewidth=2, label='Val Accuracy')
axes[1].axvline(x=phase1_end, color='red',
                linestyle='--', linewidth=2, label='Fine-tune Start')
axes[1].set_title('Validation Accuracy')
axes[1].set_xlabel('Epochs')
axes[1].set_ylabel('Accuracy')
axes[1].legend()
axes[1].grid(True, linestyle='--', alpha=0.5)

plt.suptitle('ResNet50 Transfer Learning on STL-10', fontweight='bold')
plt.tight_layout()
plt.show()